name: AoC2025
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libmpdec=4.0.0=h827c3e9_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyh0d26453_0
  - python=3.14.2=h3bc0a5a_101_cp314
  - python_abi=3.14=2_cp314
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.61.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - packaging==25.0
      - pillow==12.0.0
      - pulp==3.3.0
      - pyparsing==3.2.5
      - sympy==1.14.0
prefix: C:\Users\wyatt\anaconda3\envs\AoC2025
